### ISSUE TITLE
[FE] 이슈 작성 페이지 레이아웃 작업

### ISSUE THREAD

**Issue by silvertae** [codesquad-issue-team-05/issue-tracker-max#67]
## AS-IS
- 이슈 작성 페이지 미구현

## TO-BE
- 기능 제외 화면에 보여지는 이슈작성 페이지 레이아웃만 공통컴포넌트들 활용해서 구현하기 

### ToDo
- [x] header
  - [x] 로고 영역
  - [x] 사용자 프로필 영역
- [x] body
  - [x] 타이틀
  - [x] 컨테이너
    - [x] 제목 인풋
    - [x] 코멘트 인풋
    - [x] 사이드바
  - [x] 버튼 영역
    - [x] 작성 취소 버튼
    - [x] 작성 완료 버튼
